apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
spec:
  containers:
    - name: server
      image: my_file_server
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30950
      protocol: TCP
  selector:
    app: server